version: 1.0

# Formatters configuration
formatters:
  default:
    datefmt: '%Y-%m-%d %H:%M:%S'
    format: "%(asctime)s - [%(levelname)s - %(filename)s:%(lineno)d]: %(message)s"
  colorful:
    (): src.utils.log.ColorfulFormatter
    datefmt: '%Y-%m-%d %H:%M:%S'

# Handlers configuration
handlers:
  console:
    class: logging.StreamHandler
    formatter: colorful
    # level: DEBUG
    stream: ext://sys.stdout

  local_model: 
    class: logging.FileHandler
    formatter: default
    # level: INFO
    filename: logs/local_model.log

  global_model:
    class: logging.FileHandler
    formatter: default
    filename: logs/global_model.log

  demography_predictor:
    class: logging.FileHandler
    formatter: default
    filename: logs/demography_predictor.log

  finetuneable_local_model:
    class: logging.FileHandler
    formatter: default
    # level: INFO
    filename: logs/finetunable_local_model.log

  data_preprocessing: 
    class: logging.FileHandler
    formatter: default
    # level: INFO
    filename: logs/data_preprocessing.log

  model_experiments:
    class: logging.FileHandler
    formatter: default
    # level: INFO
    filename: logs/model_experiments.log

  api:
    class: logging.FileHandler
    formatter: default
    # level: INFO
    filename: logs/api.log

# Logger(s) configuration
loggers:
  local_model:
    level: INFO
    handlers: [console, local_model]
    propagate: no

  global_model:
    level: INFO
    handlers: [console, global_model]
    propagate: no

  demography_predictor:
    level: INFO
    handlers: [console, demography_predictor]
    propagate: no

  finetuneable_local_model:
    level: INFO
    handlers: [console, finetuneable_local_model]
    propagate: no

  data_preprocessing:
    level: INFO
    handlers: [console, data_preprocessing]
    propagate: no

  method_selection:
    level: INFO
    handlers: [console]
    propagate: no

  model_experiments:
    level: INFO
    handlers: [console, model_experiments]
    propagate: no

  api:
    level: INFO
    handlers: [console, api]
    propagate: no

  model_compare:
    level: INFO
    handlers: [console]
    propagate: no

  training:
    level: INFO
    handlers: [console]
    propagate: no

  explain:
    level: INFO
    handlers: [console]
    propagate: no
