[tool.poetry]
name = "demography-predictor"
version = "0.1.0"
description = ""
authors = ["Adnrew <ado.ponechal@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "~3.11"
torch = "^2.6.0"
scikit-learn = "^1.6.1"
pandas = "^2.2.3"
pydantic-settings = "^2.7.1"
pydantic = "^2.10.6"
optree = ">=0.13.0"
matplotlib = "^3.10.0"
colorama = "^0.4.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
