# Copyright (c) 2025 Adrián Ponechal
# Licensed under the MIT License

# Standard library imports
import pandas as pd
import pprint
from pydantic import BaseModel
from typing import Dict, List

# Custom imports
from config import Config

settings = Config()


def print_available_states(dataset_path: str) -> None:
    """
    Print available populations in the dataset.

    Args:
        dataset_path (str): Path to the dataset.
    """
    df = pd.read_csv(dataset_path)
    states = list(df["country_name"].unique())

    pprint.pprint(states)


class StatesGroups(BaseModel):
    def get_states_corresponding_group(self, state: str) -> List[str]:
        for group_states in self.model_dump().values():
            if state in group_states:
                return group_states


class StatesByWealth(StatesGroups):
    """
    Class to group states by wealth.
    """

    # High-income economies and groups

    high_income: List[str] = [
        "Antigua and Barbuda",
        "Aruba",
        "Australia",
        "Austria",
        "Bahamas, The",
        "Bahrain",
        "Barbados",
        "Belgium",
        "Brunei Darussalam",
        "Canada",
        "Channel Islands",
        "Chile",
        "Croatia",
        "Cyprus",
        "Czechia",
        "Denmark",
        "Estonia",
        "Faroe Islands",
        "Finland",
        "France",
        "Germany",
        "Greece",
        "Hong Kong SAR, China",
        "Hungary",
        "Iceland",
        "Ireland",
        "Israel",
        "Italy",
        "Japan",
        "Korea, Rep.",
        "Kuwait",
        "Latvia",
        "Liechtenstein",
        "Lithuania",
        "Luxembourg",
        "Malta",
        "Netherlands",
        "New Zealand",
        "Norway",
        "Oman",
        "Poland",
        "Portugal",
        "Puerto Rico",
        "Qatar",
        # "San Marino",
        "Saudi Arabia",
        # "Singapore",
        "Slovak Republic",
        "Slovenia",
        "Spain",
        "Sweden",
        "Switzerland",
        "Trinidad and Tobago",
        "United Arab Emirates",
        "United Kingdom",
        "United States",
        "Virgin Islands (U.S.)",
        # Groups
        "High income",
        "North America",
        "OECD members",
    ]

    # Upper-middle-income economies and groups
    upper_middle_income: List[str] = [
        "Albania",
        "Algeria",
        "Argentina",
        "Armenia",
        "Azerbaijan",
        "Belarus",
        "Bosnia and Herzegovina",
        "Botswana",
        "Brazil",
        "Bulgaria",
        "China",
        "Colombia",
        "Costa Rica",
        "Cuba",
        "Dominican Republic",
        "Ecuador",
        "Egypt, Arab Rep.",
        "Equatorial Guinea",
        "Fiji",
        "Gabon",
        "Georgia",
        "Grenada",
        "Iran, Islamic Rep.",
        "Iraq",
        "Jamaica",
        "Jordan",
        "Kazakhstan",
        "Lebanon",
        "Libya",
        "Malaysia",
        "Maldives",
        "Mauritius",
        "Mexico",
        "Montenegro",
        "Namibia",
        "North Macedonia",
        "Panama",
        "Paraguay",
        "Peru",
        "Romania",
        "Russian Federation",
        "Serbia",
        "South Africa",
        "Sri Lanka",
        "St. Kitts and Nevis",
        "St. Lucia",
        "St. Vincent and the Grenadines",
        "Suriname",
        "Thailand",
        "Tunisia",
        "Turkiye",
        "Turkmenistan",
        "Uruguay",
        "Uzbekistan",
        "Venezuela, RB",
        "Viet Nam",
        # Groups
        "Upper middle income",
        "Caribbean small states",
        "Central Europe and the Baltics",
        "Latin America & Caribbean",
        "Latin America & Caribbean (excluding high income)",
        "Latin America & the Caribbean (IDA & IBRD countries)",
        "Middle income",
    ]

    # Lower-middle-income economies and groups
    lower_middle_income: List[str] = [
        "Angola",
        "Bangladesh",
        "Bhutan",
        "Bolivia",
        "Cabo Verde",
        "Cambodia",
        "Cameroon",
        "Cote d'Ivoire",
        "Djibouti",
        "El Salvador",
        "Eswatini",
        "Ghana",
        "Guatemala",
        "Honduras",
        "India",
        "Indonesia",
        "Kenya",
        "Kyrgyz Republic",
        "Lao PDR",
        "Lesotho",
        "Mauritania",
        "Micronesia, Fed. Sts.",
        "Moldova",
        "Mongolia",
        "Morocco",
        "Myanmar",
        "Nepal",
        "Nicaragua",
        "Nigeria",
        "Pakistan",
        "Papua New Guinea",
        "Philippines",
        "Samoa",
        "Sao Tome and Principe",
        "Senegal",
        "Solomon Islands",
        "Tajikistan",
        "Tanzania",
        "Timor-Leste",
        "Tunisia",
        "Ukraine",
        "Vanuatu",
        "West Bank and Gaza",
        "Zambia",
        "Zimbabwe",
        # Groups
        "Lower middle income",
        "South Asia (IDA & IBRD)",
        "Middle East & North Africa (IDA & IBRD countries)",
        "Sub-Saharan Africa (IDA & IBRD countries)",
        "East Asia & Pacific (IDA & IBRD countries)",
        "IDA blend",
    ]

    # Low-income economies and groups
    low_income: List[str] = [
        "Afghanistan",
        "Benin",
        "Burkina Faso",
        "Burundi",
        "Central African Republic",
        "Chad",
        "Comoros",
        "Congo, Dem. Rep.",
        "Eritrea",
        "Ethiopia",
        "Gambia, The",
        "Guinea",
        "Guinea-Bissau",
        "Haiti",
        "Liberia",
        "Madagascar",
        "Malawi",
        "Mali",
        "Mozambique",
        "Niger",
        "Rwanda",
        "Sierra Leone",
        "Somalia",
        "South Sudan",
        "Sudan",
        "Syrian Arab Republic",
        "Togo",
        "Uganda",
        "Yemen, Rep.",
        # Groups
        "Low income",
        "Africa Eastern and Southern",
        "Africa Western and Central",
        "Sub-Saharan Africa",
        "Sub-Saharan Africa (excluding high income)",
        "South Asia",
        "East Asia & Pacific (excluding high income)",
        "Europe & Central Asia (excluding high income)",
        "Middle East & North Africa (excluding high income)",
        "IDA only",
        "IDA total",
        "IDA & IBRD total",
        "Heavily indebted poor countries (HIPC)",
        "Fragile and conflict affected situations",
        "Least developed countries: UN classification",
    ]


class StatesByGeolocation(StatesGroups):
    """
    Class to group states by geolocation.
    """

    asia: List[str] = [
        "Afghanistan",
        "Armenia",
        "Azerbaijan",
        "Bahrain",
        "Bangladesh",
        "Bhutan",
        "Brunei Darussalam",
        "Cambodia",
        "China",
        "Cyprus",
        "Georgia",
        "India",
        "Indonesia",
        "Iran, Islamic Rep.",
        "Iraq",
        "Israel",
        "Japan",
        "Jordan",
        "Kazakhstan",
        "Korea, Rep.",
        "Kuwait",
        "Kyrgyz Republic",
        "Lao PDR",
        "Lebanon",
        "Malaysia",
        "Maldives",
        "Mongolia",
        "Myanmar",
        "Nepal",
        "Oman",
        "Pakistan",
        "Philippines",
        "Qatar",
        "Saudi Arabia",
        # "Singapore",
        "Sri Lanka",
        "Syrian Arab Republic",
        "Tajikistan",
        "Thailand",
        "Timor-Leste",
        "Turkmenistan",
        "United Arab Emirates",
        "Uzbekistan",
        "Viet Nam",
        "West Bank and Gaza",
        "Yemen, Rep.",
    ]
    europe: List[str] = [
        "Albania",
        "Austria",
        "Belarus",
        "Belgium",
        "Bosnia and Herzegovina",
        "Bulgaria",
        "Channel Islands",
        "Croatia",
        "Czechia",
        "Denmark",
        "Estonia",
        "Faroe Islands",
        "Finland",
        "France",
        "Germany",
        "Greece",
        "Hungary",
        "Iceland",
        "Ireland",
        "Italy",
        "Latvia",
        "Liechtenstein",
        "Lithuania",
        "Luxembourg",
        "Malta",
        "Moldova",
        "Montenegro",
        "Netherlands",
        "North Macedonia",
        "Norway",
        "Poland",
        "Portugal",
        "Romania",
        "Russian Federation",
        # "San Marino",
        "Serbia",
        "Slovak Republic",
        "Slovenia",
        "Spain",
        "Sweden",
        "Switzerland",
        "Ukraine",
        "United Kingdom",
    ]
    north_america: List[str] = [
        "Canada",
        "United States",
        "Mexico",
        "Antigua and Barbuda",
        "Bahamas, The",
        "Barbados",
        "Belize",
        "Costa Rica",
        "Cuba",
        "Dominica",
        "Dominican Republic",
        "El Salvador",
        "Grenada",
        "Guatemala",
        "Haiti",
        "Honduras",
        "Jamaica",
        "Nicaragua",
        "Panama",
        "Puerto Rico",
        "St. Kitts and Nevis",
        "St. Lucia",
        "St. Vincent and the Grenadines",
        "Trinidad and Tobago",
        "Turks and Caicos Islands",
        "Virgin Islands (U.S.)",
    ]
    south_america: List[str] = [
        "Argentina",
        "Bolivia",
        "Brazil",
        "Chile",
        "Colombia",
        "Ecuador",
        "Guyana",
        "Paraguay",
        "Peru",
        "Suriname",
        "Uruguay",
        "Venezuela, RB",
    ]
    africa: List[str] = [
        "Algeria",
        "Angola",
        "Benin",
        "Botswana",
        "Burkina Faso",
        "Burundi",
        "Cabo Verde",
        "Cameroon",
        "Central African Republic",
        "Chad",
        "Comoros",
        "Congo, Dem. Rep.",
        "Congo, Rep.",
        "Cote d'Ivoire",
        "Djibouti",
        "Egypt, Arab Rep.",
        "Equatorial Guinea",
        "Eritrea",
        "Eswatini",
        "Ethiopia",
        "Gabon",
        "Gambia, The",
        "Ghana",
        "Guinea",
        "Guinea-Bissau",
        "Kenya",
        "Lesotho",
        "Liberia",
        "Libya",
        "Madagascar",
        "Malawi",
        "Mali",
        "Mauritania",
        "Mauritius",
        "Morocco",
        "Mozambique",
        "Namibia",
        "Niger",
        "Nigeria",
        "Rwanda",
        "Sao Tome and Principe",
        "Senegal",
        "Seychelles",
        "Sierra Leone",
        "Somalia",
        "South Africa",
        "South Sudan",
        "Sudan",
        "Tanzania",
        "Togo",
        "Tunisia",
        "Uganda",
        "Zambia",
        "Zimbabwe",
    ]
    oceania: List[str] = [
        "Australia",
        "Fiji",
        "Kiribati",
        "Marshall Islands",
        "Micronesia, Fed. Sts.",
        "New Zealand",
        "Palau",
        "Papua New Guinea",
        "Samoa",
        "Solomon Islands",
        "Tonga",
        "Tuvalu",
        "Vanuatu",
    ]


class OnlyRealStates(StatesGroups):
    states: List[str] = [
        "Afghanistan",
        "Albania",
        "Algeria",
        "Angola",
        "Antigua and Barbuda",
        "Argentina",
        "Armenia",
        "Australia",
        "Austria",
        "Azerbaijan",
        "Bahamas, The",
        "Bahrain",
        "Bangladesh",
        "Barbados",
        "Belarus",
        "Belgium",
        "Belize",
        "Benin",
        "Bhutan",
        "Bolivia",
        "Bosnia and Herzegovina",
        "Botswana",
        "Brazil",
        "Brunei Darussalam",
        "Bulgaria",
        "Burkina Faso",
        "Burundi",
        "Cabo Verde",
        "Cambodia",
        "Cameroon",
        "Canada",
        "Chile",
        "China",
        "Colombia",
        "Comoros",
        "Congo, Dem. Rep.",
        "Congo, Rep.",
        "Costa Rica",
        "Cote d'Ivoire",
        "Croatia",
        "Cuba",
        "Cyprus",
        "Czechia",
        "Denmark",
        "Djibouti",
        "Dominica",
        "Dominican Republic",
        "Ecuador",
        "Egypt, Arab Rep.",
        "El Salvador",
        "Equatorial Guinea",
        "Eritrea",
        "Estonia",
        "Eswatini",
        "Ethiopia",
        "Finland",
        "France",
        "Gabon",
        "Gambia, The",
        "Georgia",
        "Germany",
        "Ghana",
        "Greece",
        "Grenada",
        "Guatemala",
        "Guinea",
        "Guinea-Bissau",
        "Guyana",
        "Haiti",
        "Honduras",
        "Hungary",
        "Iceland",
        "India",
        "Indonesia",
        "Iran, Islamic Rep.",
        "Iraq",
        "Ireland",
        "Italy",
        "Jamaica",
        "Japan",
        "Jordan",
        "Kazakhstan",
        "Kenya",
        "Kiribati",
        "Korea, Rep.",
        "Kuwait",
        "Kyrgyz Republic",
        "Lao PDR",
        "Latvia",
        "Lebanon",
        "Lesotho",
        "Liberia",
        "Libya",
        "Liechtenstein",
        "Lithuania",
        "Luxembourg",
        "Madagascar",
        "Malawi",
        "Malaysia",
        "Maldives",
        "Mali",
        "Malta",
        "Marshall Islands",
        "Mauritania",
        "Mauritius",
        "Mexico",
        "Micronesia, Fed. Sts.",
        "Moldova",
        "Mongolia",
        "Montenegro",
        "Morocco",
        "Mozambique",
        "Myanmar",
        "Namibia",
        "Nepal",
        "Netherlands",
        "Nicaragua",
        "Niger",
        "Nigeria",
        "North Macedonia",
        "Norway",
        "Oman",
        "Pakistan",
        "Panama",
        "Papua New Guinea",
        "Paraguay",
        "Peru",
        "Philippines",
        "Poland",
        "Portugal",
        "Romania",
        "Russian Federation",
        "Rwanda",
        "Samoa",
        "Sao Tome and Principe",
        "Saudi Arabia",
        "Senegal",
        "Serbia",
        "Sierra Leone",
        "Slovak Republic",
        "Slovenia",
        "Somalia",
        "South Africa",
        "South Sudan",
        "Spain",
        "Sri Lanka",
        "Sudan",
        "Suriname",
        "Sweden",
        "Switzerland",
        "Syrian Arab Republic",
        "Tajikistan",
        "Tanzania",
        "Thailand",
        "Timor-Leste",
        "Togo",
        "Tonga",
        "Trinidad and Tobago",
        "Tunisia",
        "Turkiye",
        "Turkmenistan",
        "Uganda",
        "Ukraine",
        "United Arab Emirates",
        "United Kingdom",
        "United States",
        "Uruguay",
        "Uzbekistan",
        "Vanuatu",
        "Venezuela, RB",
        "Viet Nam",
        "Yemen, Rep.",
        "Zambia",
        "Zimbabwe",
        "Israel",
        "New Zealand",
    ]


def main():
    dataset_path = settings.dataset_path
    print_available_states(dataset_path=dataset_path)


if __name__ == "__main__":
    main()
